# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Craft < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.3.1/craft_2.3.1_darwin_amd64.tar.gz"
      sha256 "e63e225114718ac6288efc416f1e8b2fc429f9766d04a39c80ba3f16c0ebe460"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.3.1/craft_2.3.1_darwin_arm64.tar.gz"
      sha256 "fbc225a005313925add3a15a05a2ddb8e369483440d0cca4514c4fe50a2e6b5d"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.3.1/craft_2.3.1_linux_amd64.tar.gz"
      sha256 "b93b1a02338923e7654b8fa801ab4378d40b9d6d25e093abec89c3b3b9e1cf49"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.3.1/craft_2.3.1_linux_arm64.tar.gz"
      sha256 "1bf71ad03fa1b4b6db5083fed6e8b119c9801ace00fe61277d84544d25b131a0"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
