# This file was generated by GoReleaser. DO NOT EDIT.
cask "craft" do
  version "2.3.0"

  on_macos do
    on_intel do
      sha256 "222d03788bfb890cbff552c2663996105ef925bcddcf389b8393c5e9bf3b94c9"
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c6d325399c909421040fa4e9dc3c577a045db9da2ac94107f87858b5c07574d"
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "228339193a39333cf4dd01a918ad265b987a133f24e574c60ccc49f587036012"
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4bf1a376944f045e809169142b1cd09bdef6a733aea36d75829bd8de70352f9e"
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "craft"
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "craft"

  # No zap stanza required

end
