# This file was generated by GoReleaser. DO NOT EDIT.
cask "craft" do
  version "2.3.2"

  on_macos do
    on_intel do
      sha256 "9e21d7f150cf6c34d8225cb4362ddefb51bb59fd38fb0a34534008008fd4db56"
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0430f685d298896989dfa702e0d3ac4d16821548b28e7698137b24a265439d44"
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f40edc6e6ed37e1b7ed8b70933264f54708b498264d52eef1e4dc52065536faa"
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3793f1bb0c38fd50590f5c23e7e9a7cda5c07b2cec3ba865c6873ee3bbbb0a4c"
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "craft"
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "craft"

  # No zap stanza required

end
