# This file was generated by GoReleaser. DO NOT EDIT.
cask "craft-cli" do
  version "2.1.0"

  on_macos do
    on_intel do
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_darwin_amd64.tar.gz"
      sha256 "553529579b9daec7f2767919a3ddef7f66e2165c3a6b4eebb736b42ffe43e333"
    end
    on_arm do
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_darwin_arm64.tar.gz"
      sha256 "6cd44e3e340f43a62a9a5b6fe00cc8f8aa54ddf99743a8bada060b6eaab1c864"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_linux_amd64.tar.gz"
      sha256 "a53589b629ac0fd8fc28432d51d3fce77224c377a9b6a5d1f33f240548daaa19"
    end
    on_arm do
      url "https://github.com/tcarcao/craft/releases/download/v#{version}/craft_#{version}_linux_arm64.tar.gz"
      sha256 "fe7fd940c7ab8397b090d1de8be4aefeba93862a1dbc9b08b8eed89acadc91fd"
    end
  end

  name "craft-cli"
  desc "DDD modeling CLI — parse, lint, inspect, and generate diagrams from .craft files"
  homepage "https://github.com/tcarcao/craft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "craft-cli"

  # No zap stanza required

end
