# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT215 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.15.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.15.1/craft_2.15.1_darwin_amd64.tar.gz"
      sha256 "856f02dde9ffee2ddaa95c695f6d9753b95d2d64432c9cb7c75e364c8f8a6e25"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.15.1/craft_2.15.1_darwin_arm64.tar.gz"
      sha256 "bee5cfca3526fb187870d0bf812e66504383bde2c4599bcd23924088b77fd09b"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.15.1/craft_2.15.1_linux_amd64.tar.gz"
      sha256 "775cb9fc56caf955f66659a9fcc5b3a54f403c0b033bf1e5026c51668407ac10"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.15.1/craft_2.15.1_linux_arm64.tar.gz"
      sha256 "e687a5a232d2fb16c6d0ede9bffbd4301fb9198a92c362a4a1658fa941dea5d7"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
