# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT29 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.9.0/craft_2.9.0_darwin_amd64.tar.gz"
      sha256 "4fca5efd7b3d08421014067af8d88a7c30653520c54e2f2537e468eb2d3a3a02"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.9.0/craft_2.9.0_darwin_arm64.tar.gz"
      sha256 "6673b3bc8696af8b3309dac9162a0c0d236911937afd0d1e4a4d6758ba27395a"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.9.0/craft_2.9.0_linux_amd64.tar.gz"
      sha256 "a747e8ad2d9de6c0b93f0523cf6833fd870d3a24213adf76593e55eff12fed92"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.9.0/craft_2.9.0_linux_arm64.tar.gz"
      sha256 "a4e5a06848ad532a49ac1bb423cc4f652437e49cc6964747f0d3d4a81a129f26"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
