# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT213 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.13.0/craft_2.13.0_darwin_amd64.tar.gz"
      sha256 "96e7e684b8bc5bde51190b9ec756bb65c0d17e04fdd2a3a391d5c632ce7f895f"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.13.0/craft_2.13.0_darwin_arm64.tar.gz"
      sha256 "1b11eb79c02edac1e4462c70457066272bfe6af7bec36327ef523137364fbdd2"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.13.0/craft_2.13.0_linux_amd64.tar.gz"
      sha256 "baf57afc5ffa878d74c58ae7b59bc3ebb9a33c014efb4f66a0ed0671ee71bc7c"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.13.0/craft_2.13.0_linux_arm64.tar.gz"
      sha256 "244fb9cd8c38448dd0562523a93164b4fff76578cc1b482e2f9dfc2baea31da3"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
