# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT214 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.14.0/craft_2.14.0_darwin_amd64.tar.gz"
      sha256 "70e6369bd7f6dec6b2aa49134386f0d148d0505243c76ec5cd69a4f4863af831"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.14.0/craft_2.14.0_darwin_arm64.tar.gz"
      sha256 "d58fce6d847e73859bfa91d868a1391001bac6947a112b3783471cc65f647483"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.14.0/craft_2.14.0_linux_amd64.tar.gz"
      sha256 "515a381ce9683257cbbe2f6eb04f173b0c222c636ac13ba3b733bed61774840f"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.14.0/craft_2.14.0_linux_arm64.tar.gz"
      sha256 "5236523d1c69a4364f4b6dea4319a411042936edecdab7c10d16c83254ef69ed"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
