# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT25 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.1/craft_2.5.1_darwin_amd64.tar.gz"
      sha256 "cd48213901c8e5b8312c3228d37aecf8153e491f5745f92c6a5ee590b8655a25"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.1/craft_2.5.1_darwin_arm64.tar.gz"
      sha256 "7ab9392d2ff7e61c8eee31711b815204164e9144ccc323999cbcdf0a3964165f"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.1/craft_2.5.1_linux_amd64.tar.gz"
      sha256 "ad708102bc1b202a26c5a76b1b47b659ce17b2a8296eb4411ae89a523b82e9ea"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.1/craft_2.5.1_linux_arm64.tar.gz"
      sha256 "d121dcfb96637cb14b8b6987983efc82defaff6e90413ace6c720c8415dc8a2c"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
