# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftCli < Formula
  desc "DDD modeling CLI — parse, lint, inspect, and generate diagrams from .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.1.0/craft_2.1.0_darwin_amd64.tar.gz"
      sha256 "8dcc1f5f26903df814471ffc57f9dfae290b4592fea8d569571d743247a79526"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.1.0/craft_2.1.0_darwin_arm64.tar.gz"
      sha256 "f4cefeab1584981556780c9c15a077e289e56933490677d403cc199e6f871a3f"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.1.0/craft_2.1.0_linux_amd64.tar.gz"
      sha256 "8acf7fe9dff2b27e98a5a3696f02f37697889a9afd00cb0318ccc6f811a197cb"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.1.0/craft_2.1.0_linux_arm64.tar.gz"
      sha256 "57d5d441d8b46731280e0d38dc119f055668c68806572ab8031c4912b5426e62"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  test do
    system "#{bin}/craft", "--help"
  end
end
