# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT24 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.4.0/craft_2.4.0_darwin_amd64.tar.gz"
      sha256 "29bb4f2576cc9ce1dffc2eafe39cf692fbd8dc901b3c439c88d79e622f414d04"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.4.0/craft_2.4.0_darwin_arm64.tar.gz"
      sha256 "b93177330443a62c62babca79d6cb8609b598bc99d9292ee53b670699b58bcff"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.4.0/craft_2.4.0_linux_amd64.tar.gz"
      sha256 "6218486914945db865f6e8aac8e2407442cd08bd8b715fbe5de90a215800efae"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.4.0/craft_2.4.0_linux_arm64.tar.gz"
      sha256 "fa2fea0901e7f0f9b4292ffa139ff8147c95b9d40b4840fa48dea87999b93bd8"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
