# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT210 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.10.0/craft_2.10.0_darwin_amd64.tar.gz"
      sha256 "ee90b764fccb213bed0476ca7acebcdd882361c98db0a4599012c3a9311ed37e"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.10.0/craft_2.10.0_darwin_arm64.tar.gz"
      sha256 "0380754cb58f24287dab786f6c82c55b8c4957496b87afecd7c94ff8d11524e4"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.10.0/craft_2.10.0_linux_amd64.tar.gz"
      sha256 "a7a241b252c451612f384a609fccd56da8b3cab3a68342f80522e427dd417f70"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.10.0/craft_2.10.0_linux_arm64.tar.gz"
      sha256 "c321a1bdd77708f9e1c26bb7b927aed414470c5ce7d6a197edaf324c5c27da77"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
