# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT217 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.17.0/craft_2.17.0_darwin_amd64.tar.gz"
      sha256 "dc745e21a600c3e23d85b0d9ea56f73bf770dc147ad8be1c4cdaf957090c589b"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.17.0/craft_2.17.0_darwin_arm64.tar.gz"
      sha256 "a03d8bb7f788edd6b334ed9e49acd4b4e6de91d1ea8aef00753566c35408bf79"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.17.0/craft_2.17.0_linux_amd64.tar.gz"
      sha256 "2032edfacd8d958c9f8e93d15aa2552ed9323d7ce9511515f83904a21d3658be"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.17.0/craft_2.17.0_linux_arm64.tar.gz"
      sha256 "2d3aac0304a62f30dab374a2cd3bed68cfacfbd76655b497d7d63b162db88691"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
