# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT28 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.8.0/craft_2.8.0_darwin_amd64.tar.gz"
      sha256 "0c29c2d0c7d6621c410b78e4147b25e112fc0a622216cb7d084ea57eae138cf5"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.8.0/craft_2.8.0_darwin_arm64.tar.gz"
      sha256 "6085416d43237bacf65992573a1b3657e2175ac85b6fb3ee861cc6a5a5c3869d"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.8.0/craft_2.8.0_linux_amd64.tar.gz"
      sha256 "475b8235cf82a2463bec491bdff2b7e0abd576e475098ddbdf98eee20f1cb2fd"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.8.0/craft_2.8.0_linux_arm64.tar.gz"
      sha256 "65fa90de8275bd7e931dedad05d1bdf22f52a61a1f77055b5a9618fd70619030"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
