# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT25 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.2/craft_2.5.2_darwin_amd64.tar.gz"
      sha256 "6753c2c0b77396e30cddd9a0cd9cb1a97f9961686a3adbed9b9340a2c2ebca78"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.2/craft_2.5.2_darwin_arm64.tar.gz"
      sha256 "f90e7e4fbd95b50703f1f7a8ccbde7acb2e67c1785c87a8ba196c32c64e90a96"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.2/craft_2.5.2_linux_amd64.tar.gz"
      sha256 "ccff4478d4a68cc109f6c4dcca1ac5b08774fb9d25db8faa0e1aea10055b93fd"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.2/craft_2.5.2_linux_arm64.tar.gz"
      sha256 "96a9756ff54c187f6267dc7e55fb14654f71752d0655bbed4267f0133ea4fa11"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
