# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftCli < Formula
  desc "DDD modeling CLI — parse, lint, inspect, and generate diagrams from .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.1.0/craft_2.1.0_darwin_amd64.tar.gz"
      sha256 "23395a87f2c9ff346e51ab9e37218d09d472d4e62c6cb7b5a665798897fd4f8e"

      define_method(:install) do
        bin.install "craft-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.1.0/craft_2.1.0_darwin_arm64.tar.gz"
      sha256 "dd13a3b305e711f021ae70d324d5f49d7cc6d66917f2c5b954e954344aa2facb"

      define_method(:install) do
        bin.install "craft-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.1.0/craft_2.1.0_linux_amd64.tar.gz"
      sha256 "1312f961e430a7f6547c1d2e8472b532fb0c5be3d5ea74e1b79a2f1bb452440f"
      define_method(:install) do
        bin.install "craft-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.1.0/craft_2.1.0_linux_arm64.tar.gz"
      sha256 "f228c088897f670e3c49079bc89e76b98c10ddae5d83c15a3cf75e567d932f5e"
      define_method(:install) do
        bin.install "craft-cli"
      end
    end
  end

  test do
    system "#{bin}/craft-cli", "--help"
  end
end
