# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT217 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.17.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.17.2/craft_2.17.2_darwin_amd64.tar.gz"
      sha256 "562e08bf7cfef74e749fc63565f1481b72b841c9b7d782597b7c028f4428db40"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.17.2/craft_2.17.2_darwin_arm64.tar.gz"
      sha256 "8db79a3b2048b5ad8b0817975bd53bf238a0b8528115d537a42c0f7c26108ae1"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.17.2/craft_2.17.2_linux_amd64.tar.gz"
      sha256 "a231be2e4341c5f8da4e77b20cc486206371581f6af8af63ecd4d1a02b31899c"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.17.2/craft_2.17.2_linux_arm64.tar.gz"
      sha256 "0b8c986d6aa2666c5d5e321fc522855f4b49ce5143ec8280e0f040f240d79393"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
