# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT211 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.11.0/craft_2.11.0_darwin_amd64.tar.gz"
      sha256 "355ab94a3e18bca99f656f14d51e440d7c59c1a4c3ff5020b96835d6da7f7b24"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.11.0/craft_2.11.0_darwin_arm64.tar.gz"
      sha256 "31ff52c47e053f26b3729efa556533f555bbdf107822b8ad8eb0dc4e96c360f2"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.11.0/craft_2.11.0_linux_amd64.tar.gz"
      sha256 "210ecb7ffdfca2b838db49665766fa093dfab9ad5a0c40f7dee8544b9b1099cb"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.11.0/craft_2.11.0_linux_arm64.tar.gz"
      sha256 "9ad65711066e50dee588c980269d5730ccd58870a3aaae15f733a45030202758"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
