# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT25 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.3/craft_2.5.3_darwin_amd64.tar.gz"
      sha256 "62e0a77976109bc86ae4cdcada3d2a5cd16392d17d673a8516a90f9142a72176"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.3/craft_2.5.3_darwin_arm64.tar.gz"
      sha256 "7f6122f16d8aba13bf78b2b54db66a452e86f23b0b515c8177f385e626016a6a"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.3/craft_2.5.3_linux_amd64.tar.gz"
      sha256 "49f688cd528a3913a4252edbccb36b08555daebc546ed1763ae015484208a351"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.5.3/craft_2.5.3_linux_arm64.tar.gz"
      sha256 "c46a04534a44712fa47370921c08a6550d32522d8f31d3bdfceccfaa0e175c3f"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
