# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftCli < Formula
  desc "DDD modeling CLI — parse, lint, inspect, and generate diagrams from .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.2.0/craft_2.2.0_darwin_amd64.tar.gz"
      sha256 "deb6175ea35a96b7a8414a25b504d349136c285d65f319cdbbba25cfb188386a"

      define_method(:install) do
        bin.install "craft-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.2.0/craft_2.2.0_darwin_arm64.tar.gz"
      sha256 "64f29ddda8ee7a828aa9838941e732877896da1583b5287f581b11de5adc131f"

      define_method(:install) do
        bin.install "craft-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.2.0/craft_2.2.0_linux_amd64.tar.gz"
      sha256 "ac1a69feb74b1a2003234346ac6131c3c960bad80cf6c37cf06a9e63e7685464"
      define_method(:install) do
        bin.install "craft-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.2.0/craft_2.2.0_linux_arm64.tar.gz"
      sha256 "d838feb9cbeb531094246430fac23177dcde6b674d34f8c5e20dfdf71fddab0f"
      define_method(:install) do
        bin.install "craft-cli"
      end
    end
  end

  test do
    system "#{bin}/craft-cli", "--help"
  end
end
