# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftAT27 < Formula
  desc "DDD modeling CLI with language server — parse, lint, inspect, visualize, and edit .craft files"
  homepage "https://github.com/tcarcao/craft"
  version "2.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcarcao/craft/releases/download/v2.7.0/craft_2.7.0_darwin_amd64.tar.gz"
      sha256 "2fb6da0e9a8b80c7b29be75ea52c5fc10ffb2878b3248a30109f9f4b623f8a94"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcarcao/craft/releases/download/v2.7.0/craft_2.7.0_darwin_arm64.tar.gz"
      sha256 "c8f8ed402613d0daa68bb50b1c4b442624572f3d7a2fe633487348bf4447c7cc"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.7.0/craft_2.7.0_linux_amd64.tar.gz"
      sha256 "c59f9fcb590a16d44565274c8bb604e6cc62b1cc26f3624f8d63b14561e67840"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcarcao/craft/releases/download/v2.7.0/craft_2.7.0_linux_arm64.tar.gz"
      sha256 "933c3fb92bcf86ed7316628be90a6cb06ff63b45f53c1f1490091b1a352bfe08"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
